### ISSUE TITLE
Programmatically catch breaking API changes 

### ISSUE THREAD

**Issue by stirby** [coder/internal#156]
Breaking changes to the API, such as a new status code or differed type, go undetected by our tests. The API is validated by the `codersdk.Client` which is updated alongside the server. So no warnings are raised when api breaking changes occur.

This blind spot leads to us expecting engineers to manually catch breaking API changes in the PR review process. 

We should identify these programmatically _without_ adding a chunk of cross-version tests, leveraging something like [`swagger-diff`](https://swagger.io/blog/api-development/using-swagger-to-detect-breaking-api-changes/). 

This recently caused a minor regression in [v2.14.0](https://github.com/coder/coder/releases/tag/v2.14.1), where a status code change slipped into our release.

This tool should catch:
- Success status code changes for existing apis: `// @Success 200`
- Removed routes: `// @Router`
- Removed params: `// @Param`
- Type differences on params and success **if fields are removed** (json adding fields is ok)

**Comment by matifali** [comment]
What about a workflow to run all tests from the previous release, i.e., `release/2.15` branch, while building the server from the next release branch, `release/2.16`? Would it be able to catch any breaking changes in the new release?
We can trigger this workflow when a new `release/*` branch is cut and as part of `release.yaml` for additional safety.

Something like the below could work,

```yaml
name: Release version compatibility

on:
  push:
    branches:
      - 'release/*'

jobs:
  build_new_release_assets:
    steps:
      - Checkout code in new release branch
      - Build new release assets
      - Upload built assets as an artifact

  test_previous_release_with_new_assets:
    needs: build_new_release_assets
    steps:
      - Checkout previous release branch
      - Download new release assets
      - Run tests in previous release branch using new assets
```
